import type { Metadata } from "next";
import { Inter } from "next/font/google";  // Using Inter font
import "./globals.css"; // Adjust path if necessary

// Load Inter font from Google Fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`} // Apply the Inter font
      >
        {children}
      </body>
    </html>
  );
}
